version: '3'
services:
  bj:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bj
    networks:
      - bj
    ports:
      - '4200:4200'
    environment:
     - HOST=0.0.0.0
    command: npm run serve:ssr
    volumes:
    # Mounts the project directory on the host to /ng-app inside the container,
    # allowing you to modify the code without having to rebuild the image.
     - .:/ng-app
    # Just specify a path and let the Engine create a volume.
    # Data present in the base image at the specified mount point will be copied
    # over to the new volume upon volume initialization.
    # node_modules from this new volume will be used and not from your local dev env.
     - /ng-app/node_modules/
networks:
  bj:
    driver: bridge
